name: Terraform Security Scout CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  terraform-check:

    name: Terraform Validate

    runs-on: ubuntu-latest


    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: terraform


      - name: Terraform Init
        run: terraform init
        working-directory: terraform


      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform
